---
- name: Download elasticsearch.yml
  get_url:
    dest: /opt
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.0-amd64.deb
    owner: ubuntu
    
    
- name: Install elasticsearch
  apt:
    deb: /opt/elasticsearch-7.8.0-amd64.deb
    state: present
    