---
- name: Updating cache "apt-get update"
  apt:
    update_cache: yes
    
- name: Install OpenJDK
  apt: 
    name: default-jdk
    state: present

- name: Installing Maven 
  apt:
   name: maven
   state: present


